version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible
    build:
      context: jenkins-ansible     
    ports:
      - "8085:8080"
    dns:
      - 8.8.8.8
      - 9.9.9.9
      - 192.168.5.13
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - D:/kruger-projects/prescriptivoCD/max-prescriptivocd-parent/max-prescriptivocd-services/build/libs:/var/jenkins_deploy
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: centos7
    volumes:
      - $PWD/aws-s3.sh:/tmp/script.sh
    networks:
      - net
  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - $PWD/db_data:/var/lib/mysql
    networks:
      - net
networks:
  net:
